spring:
    application:
        name: appointment2206082612
    datasource:
        url: jdbc:postgresql://db:5432/appointment
        username: postgres
        password: secret99
    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create

server:
    port: 8082

appointment2206082612:
  app:
    jwtSecret: "pAefhuJaJRueqnyferVLGHOwOjfQhysY"
    jwtExpirationMs: 86400000
