spring:
  main:
    allow-circular-references: true
  application:
    name: insurance2206827592
  datasource:
    url: jdbc:postgresql://localhost:15001/insurance
    username: tk-apap-37
    password: tk-apap-37
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

insurance2206827592:
  app:
    jwtSecret: "HasahZEdlrHVvnBMIlKPAoXFRILWdwVAuaGT"
    jwtExpirationMs: 86400000